variable "vpc_cidr_block" {}
variable "env_prefix" {}
variable "my_ip" {}
variable "instance_type" {}
variable "public_cidr_blocks" {}
variable "private_cidr_blocks" {}
variable "cluster_name" {}
variable "vpc_name" {}
variable "aws_region" {}
variable "k8_version" {}
variable "user_for_admin_role" {}
variable "user_for_dev_role" {}
variable "gitops_url" {}
variable "gitops_username" {}
variable "gitops_password" {}